name: test
on:
  pull_request:
    paths:
    - sob/**
    - pyproject.toml
    - setup.py
    - setup.cfg
    - tests/**
    - requirements.txt
    - tox.ini
    - .github/**
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python:
        - 3.7
        - 3.8
        - 3.9
        - '3.10'
        - 3.11
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: install
      run: make ci-install
    - name: test
      run: make test
  distribute:
    if: github.ref == 'refs/heads/main'
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install
      run: make ci-install
    - name: distribute
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: make distribute
